// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {main} from '../models';

export function ConnectDB(arg1:config.DBConfig):Promise<void>;

export function DisconnectDB():Promise<void>;

export function FetchSchemas():Promise<Array<string>>;

export function FetchTableSchema(arg1:string):Promise<Array<main.ColumnInfo>>;

export function FetchTables():Promise<Array<string>>;

export function GetCodePreview(arg1:string):Promise<string>;

export function GetCodePreviewMultiple(arg1:Array<string>):Promise<Record<string, string>>;

export function GetConnectionStatus():Promise<main.ConnectionStatus>;

export function GetCurrentSchema():Promise<string>;

export function GetSavedConfig():Promise<config.DBConfig>;

export function Greet(arg1:string):Promise<string>;

export function IsPostgres():Promise<boolean>;

export function SaveAllToDirectory(arg1:string):Promise<Array<string>>;

export function SaveCodeToFile(arg1:string,arg2:string):Promise<void>;

export function SaveSelectedToDirectory(arg1:Array<string>,arg2:string):Promise<Array<string>>;

export function SetSchema(arg1:string):Promise<void>;
