// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectDB(arg1) {
  return window['go']['main']['App']['ConnectDB'](arg1);
}

export function DisconnectDB() {
  return window['go']['main']['App']['DisconnectDB']();
}

export function FetchSchemas() {
  return window['go']['main']['App']['FetchSchemas']();
}

export function FetchTableSchema(arg1) {
  return window['go']['main']['App']['FetchTableSchema'](arg1);
}

export function FetchTables() {
  return window['go']['main']['App']['FetchTables']();
}

export function GetCodePreview(arg1) {
  return window['go']['main']['App']['GetCodePreview'](arg1);
}

export function GetCodePreviewMultiple(arg1) {
  return window['go']['main']['App']['GetCodePreviewMultiple'](arg1);
}

export function GetConnectionStatus() {
  return window['go']['main']['App']['GetConnectionStatus']();
}

export function GetCurrentSchema() {
  return window['go']['main']['App']['GetCurrentSchema']();
}

export function GetSavedConfig() {
  return window['go']['main']['App']['GetSavedConfig']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function IsPostgres() {
  return window['go']['main']['App']['IsPostgres']();
}

export function SaveAllToDirectory(arg1) {
  return window['go']['main']['App']['SaveAllToDirectory'](arg1);
}

export function SaveCodeToFile(arg1, arg2) {
  return window['go']['main']['App']['SaveCodeToFile'](arg1, arg2);
}

export function SaveSelectedToDirectory(arg1, arg2) {
  return window['go']['main']['App']['SaveSelectedToDirectory'](arg1, arg2);
}

export function SetSchema(arg1) {
  return window['go']['main']['App']['SetSchema'](arg1);
}
